### ISSUE TITLE
Оборванное предложение

### ISSUE THREAD

**Issue by SanSYS** [dyp2000/Russian-Armstrong-Erlang#46]
Файл https://github.com/dyp2000/Russian-Armstrong-Erlang/raw/master/pdf/fullbook.pdf
Наличие номера страницы в pdf было бы полезным, в таких случаях )
![git-erl-tr-err](https://cloud.githubusercontent.com/assets/5781038/6768860/f5d2472e-d092-11e4-84d0-b7b346cd4e7f.png)

**Comment by dyp2000** [comment]
Так должно быть:

В Windows `erl` из консоли сработает только, если он установлен и
переменная окружения PATH указывает на его исполняемый файл. Если
вы установили Эрланг в Windows стандартным путем, то сможете его
вызвать через меню Пуск > Все Программы > Erlang OTP. В приложении В
я рассказываю, как запустить Эрланг в Windows с помощью MinGW и MSYS.

Исправлено.
Новый вариант книги доступен здесь: https://www.gitbook.com/book/dyp2000/russian-armstrong-erlang/details
