### ISSUE TITLE
Неправильная фраза

### ISSUE THREAD

**Issue by smila001** [dyp2000/Russian-Armstrong-Erlang#49]
Есть подозрение, что следующая фраза в главе 5 является неправильной

Вы должны также знать, что сопоставление условия функции всегда подразумевает точное соответствие шаблона, так что если вы определите функцию F = fun(12) -> ... end, то попытка вычислить F(12) не удастся.

**Comment by dyp2000** [comment]
31.07.15 14:09, Ivan Suvorov пишет:
>
> Есть подозрение, что следующая фраза в главе 5 является неправильной
>
> Вы должны также знать, что сопоставление условия функции всегда 
> подразумевает точное соответствие шаблона, так что если вы определите 
> функцию F = fun(12) -> ... end, то попытка вычислить F(12) не удастся.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dyp2000/Russian-Armstrong-Erlang/issues/49>.
>
Поправил там надо было F(12.0)

-- 
С уважением, Денис Парыгин
E-Mail: den@rest.ru
Группа компаний "РЭСТ"
http://stm.rest.ru
Тел. (34376) 5-22-42
